schema_version: "1.0.0"
last_updated: "2025-08-09T11:48:00.000Z"
drift_detection_framework: "version_triggered_optimization"

# File patterns to monitor for version changes
watch_patterns:
  wordpress_plugins: "wp-content/plugins/*/readme.txt"
  composer_dependencies: "composer.lock"
  npm_dependencies: "package-lock.json"
  python_dependencies: "requirements.txt"
  fusion_config: "configs/fusion/*.yaml"
  fusion_scripts: "scripts/*.py"

# Actions to execute when drift is detected
on_change:
  rebuild_ledger:
    script: "scripts/fuse-ledger.py"
    args: ["--force"]
    timeout_minutes: 15
    
  evaluate_fusion:
    script: "scripts/evaluate-fusion.py" 
    args: ["--scenarios", "configs/fusion/eval_scenarios.yaml", "--iterations", "2"]
    timeout_minutes: 30
    
  tune_parameters:
    script: "scripts/tune-overlay.py"
    args: ["--grid-size", "small"]
    timeout_minutes: 45
    depends_on: ["rebuild_ledger"]

# Quality gates for accepting drift-triggered changes
quality_gates:
  min_specificity_gain: 0.10
  min_operationality_gain: 0.08
  min_rationale_density_gain: 0.05
  max_performance_degradation: -0.05
  min_rule_validation_score: 0.75
  
  # Statistical significance requirements
  min_scenarios_improved: 3
  min_statistical_confidence: 0.70
  
  # Version change thresholds
  version_change_triggers:
    major: true      # Always trigger on major version changes
    minor: true      # Trigger on minor version changes
    patch: false     # Skip patch-only changes unless accumulated

# Drift detection settings  
detection_settings:
  check_interval_hours: 6
  max_accumulated_patch_changes: 5
  version_pattern_regex: "Version:\\s*(\\d+\\.\\d+\\.\\d+)"
  changelog_lookback_days: 30
  
  # File modification tracking
  track_file_hashes: true
  hash_algorithm: "sha256"
  ignore_whitespace_changes: true

# Notification and reporting
notifications:
  slack_webhook: null  # Set externally
  email_recipients: []
  github_pr_integration: true
  
reporting:
  generate_drift_summary: true
  include_performance_impact: true
  create_changelog_entry: true
  archive_previous_versions: true

# Rollback settings
rollback_policy:
  auto_rollback_on_failure: true
  rollback_threshold_degradation: -0.15
  max_rollback_attempts: 2
  rollback_cooldown_hours: 24

# Version management
version_management:
  bump_strategy: "semantic"  # semantic, patch, none
  tag_releases: true
  create_pr_on_changes: true
  pr_title_template: "🔄 Auto-drift: {change_summary} (+{improvement:.2f})"
  pr_description_template: |
    ## Drift Detection Results
    
    **Triggered by:** {trigger_files}
    **Changes detected:** {change_count} files modified
    
    ### Performance Impact
    - Specificity improvement: {specificity_delta:+.3f}
    - Operationality improvement: {operationality_delta:+.3f}
    - Overall improvement: {overall_delta:+.3f}
    
    ### Quality Gates Status
    {quality_gates_status}
    
    ### Modified Components
    {modified_components}
    
    *This PR was automatically generated by drift detection.*

# Historical tracking
history:
  max_drift_events_stored: 100
  retention_days: 365
  performance_trend_analysis: true
  
# Error handling
error_handling:
  max_consecutive_failures: 3
  failure_notification_threshold: 2
  auto_disable_on_repeated_failure: true
  manual_intervention_required: false

# Integration settings
integrations:
  git:
    auto_commit: true
    commit_message_template: "drift: auto-update from {trigger} (+{improvement:.2f})"
    branch_prefix: "drift/"
    
  ci_cd:
    trigger_pipeline_on_change: true
    skip_tests_if_minor_change: false
    deploy_on_quality_gate_pass: false