schema_version: "1.0.0"
last_updated: "2025-08-09T11:52:00.000Z"
slo_framework: "fusion_production_safety"

# Service Level Objectives for Fusion Engine
service_level_objectives:
  fusion_overlay_applied_rate:
    description: "Percentage of requests where fusion overlay is successfully applied"
    target: 0.95
    measurement_window_minutes: 60
    alert_threshold: 0.92
    
  fusion_errors_rate:
    description: "Error rate for fusion processing pipeline" 
    target: 0.005  # 0.5% maximum error rate
    measurement_window_minutes: 30
    alert_threshold: 0.01
    
  fusion_response_latency_p95:
    description: "95th percentile response latency for fusion processing"
    target_ms: 2000
    measurement_window_minutes: 15
    alert_threshold_ms: 3000
    
  fusion_delta_tokens:
    description: "Token count increase compared to baseline median"
    target_percentage: 0.12  # 12% maximum increase
    measurement_window_minutes: 60
    alert_threshold_percentage: 0.20
    
  cross_judge_consensus:
    description: "Agreement rate between primary and secondary judges"
    target: 0.85
    measurement_window_minutes: 120
    alert_threshold: 0.75
    
  rule_validation_pass_rate:
    description: "Percentage of responses passing rule validation"
    target: 0.90
    measurement_window_minutes: 60
    alert_threshold: 0.80

# Circuit Breaker Configurations
circuit_breakers:
  fusion_primary:
    description: "Main fusion overlay processing circuit"
    failure_threshold: 5
    recovery_timeout_seconds: 300
    half_open_max_calls: 3
    trip_conditions:
      - metric: "fusion_errors_rate"
        threshold: 0.02
        consecutive_violations: 3
      - metric: "fusion_response_latency_p95"
        threshold_ms: 5000
        consecutive_violations: 2
        
  judge_fusion:
    description: "Cross-judge evaluation circuit"
    failure_threshold: 3
    recovery_timeout_seconds: 180
    half_open_max_calls: 2
    trip_conditions:
      - metric: "cross_judge_consensus"
        threshold: 0.60
        consecutive_violations: 3
        
  parameter_tuning:
    description: "Parameter auto-tuning circuit"
    failure_threshold: 2
    recovery_timeout_seconds: 600
    half_open_max_calls: 1
    trip_conditions:
      - metric: "parameter_tuning_success_rate"
        threshold: 0.50
        consecutive_violations: 2

# Degradation Strategies
degradation_strategies:
  fusion_overlay_degraded:
    description: "Fallback when fusion overlay fails"
    actions:
      - disable_overlay: true
      - use_baseline_model: true
      - log_degradation_event: true
      - notify_operations: true
      
  judge_evaluation_degraded:
    description: "Fallback when cross-judge evaluation fails"
    actions:
      - use_single_judge: "primary"
      - reduce_rule_validation: true
      - log_degradation_event: true
      
  parameter_tuning_degraded:
    description: "Fallback when parameter tuning fails"
    actions:
      - use_last_known_good_params: true
      - disable_auto_tuning: true
      - schedule_manual_review: true

# Monitoring and Alerting
monitoring:
  metrics_collection_interval_seconds: 30
  slo_evaluation_interval_seconds: 60
  circuit_breaker_check_interval_seconds: 10
  
  dashboards:
    - name: "Fusion Engine Health"
      metrics: ["fusion_overlay_applied_rate", "fusion_errors_rate", "fusion_response_latency_p95"]
    - name: "Quality Assessment"
      metrics: ["cross_judge_consensus", "rule_validation_pass_rate", "fusion_delta_tokens"]
    - name: "Circuit Breaker Status"
      circuits: ["fusion_primary", "judge_fusion", "parameter_tuning"]

alerting:
  channels:
    slack:
      webhook_url: null  # Set externally
      severity_levels: ["critical", "warning"]
      
    email:
      recipients: []
      severity_levels: ["critical"]
      
    pagerduty:
      integration_key: null  # Set externally
      severity_levels: ["critical"]

  alert_rules:
    - name: "Fusion SLO Breach"
      condition: "slo_target_missed"
      severity: "warning"
      description: "Fusion engine SLO targets not being met"
      
    - name: "Circuit Breaker Open"
      condition: "circuit_breaker_open"
      severity: "critical"
      description: "Critical fusion circuit breaker has opened"
      
    - name: "High Error Rate"
      condition: "fusion_errors_rate > 0.02"
      severity: "critical" 
      description: "Fusion engine error rate exceeds acceptable limits"

# Recovery Procedures
recovery_procedures:
  automatic:
    circuit_breaker_recovery:
      enabled: true
      max_auto_recovery_attempts: 3
      recovery_verification_checks: ["health_check", "basic_functionality"]
      
    slo_breach_response:
      enabled: true
      actions: ["increase_monitoring_frequency", "trigger_health_check", "log_detailed_metrics"]
      
  manual:
    escalation_procedures:
      - level: 1
        trigger: "slo_breach_duration > 300s"
        action: "notify_on_call_engineer"
        
      - level: 2
        trigger: "circuit_breaker_open_duration > 600s"
        action: "notify_engineering_manager"
        
      - level: 3
        trigger: "system_degradation_duration > 1800s"
        action: "notify_engineering_director"

# Health Checks
health_checks:
  fusion_engine:
    endpoint: "/health/fusion"
    timeout_ms: 5000
    interval_seconds: 30
    healthy_status_codes: [200]
    
  judge_system:
    endpoint: "/health/judges"
    timeout_ms: 3000
    interval_seconds: 45
    healthy_status_codes: [200]
    
  parameter_tuning:
    endpoint: "/health/tuning"
    timeout_ms: 10000
    interval_seconds: 300
    healthy_status_codes: [200]

# Performance Baselines
performance_baselines:
  fusion_overlay_response_time:
    baseline_ms: 1200
    acceptable_deviation_percentage: 20
    measurement_period_days: 7
    
  cross_judge_evaluation_time:
    baseline_ms: 800
    acceptable_deviation_percentage: 30
    measurement_period_days: 7
    
  parameter_optimization_time:
    baseline_minutes: 15
    acceptable_deviation_percentage: 50
    measurement_period_days: 30

# Data Retention
data_retention:
  slo_metrics_days: 90
  circuit_breaker_events_days: 30
  performance_metrics_days: 365
  alert_history_days: 180